version: '3.8'

services:
  backend:
    build: ./backend
    container_name: boaobra_api
    restart: always
    volumes:
      - dados_persistentes:/app/dados
      - ./backend/assets:/app/src/assets
    environment:
      - DB_TYPE=mssql
      - DB_SERVER=host.docker.internal
      - DB_NAME=BD_App
      - DB_USER=sysdba
      - DB_PASSWORD=masterkey

      - SECRET_KEY=sua_chave_secreta_super_segura
    extra_hosts:
      - "host.docker.internal:host-gateway"

    ports:
      - "8032:8000"  

  frontend:
    build: ./frontend
    container_name: boaobra_web
    restart: always
    
    ports:
      - "8022:80"    
    depends_on:
      - backend

volumes:
  dados_persistentes:
