version: '3.8'

services:
  backend:
    build: ./backend
    container_name: boaobra_api
    restart: always
    volumes:
      - dados_persistentes:/app/dados
      - ./backend/assets:/app/src/assets
    environment:
      - SECRET_KEY=sua_chave_secreta_super_segura
    ports:
      - "8032:8000"  

  frontend:
    build: ./frontend
    container_name: boaobra_web
    restart: always
    
    ports:
      - "8022:80"    
    depends_on:
      - backend
