version: '3.8'

services:
  backend:
    build: ./backend
    container_name: boaobra_api_dev
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
      - ./dados_api_dev:/app/dados
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=desenvolvimento

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev 
    container_name: boaobra_web_dev
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    ports:
      - "5173:5173" 
    depends_on:
      - backend
